export const optionsTipoPower = [
    { value: '1', label: 'Absorción de energía' },
    { value: '2', label: 'Artes Marciales' },
    { value: '3', label: 'Electricidad' },
    { value: '4', label: 'Campo de Fuerza' },
    { value: '5', label: 'Congelar' },
    { value: '6', label: 'Durabilidad Regenerativa' },
    { value: '7', label: 'Escala Paredes' },
    { value: '8', label: 'Extensión' },
    { value: '9', label: 'Fuerza del Destino' },
    { value: '10', label: 'Fuerza sobrehumana' },
    { value: '11', label: 'Hechicero' },
    { value: '12', label: 'Hypnosis' },
    { value: '13', label: 'Ilusionista ' },
    { value: '14', label: 'Indestructible' },
    { value: '15', label: 'Inteligencia normal' },
    { value: '16', label: 'Invisibilidad' },
    { value: '17', label: 'Lanza truenos' },
    { value: '18', label: 'Manipulacion metal' },
    { value: '19', label: 'Poder Cosmico' },
    { value: '20', label: 'Proyeccion Astral' },
    { value: '21', label: 'Rayos opticos' },
    { value: '22', label: 'Telepatia' },
    { value: '23', label: 'Teletransportacion' },
    { value: '24', label: 'Velocidad Supersonica' },
    { value: '25', label: 'Volar' }
]
